In [1]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine
import matplotlib.pyplot as plt

# –ü—Ä–æ–≤–µ—Ä—è–µ–º –≤–µ—Ä—Å–∏—é –±–∏–±–ª–∏–æ—Ç–µ–∫
print("Pandas version:", pd.__version__)

Pandas version: 2.1.1

In [10]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, text
from datetime import datetime, timedelta
import random

# –ü–æ–¥–∫–ª—é—á–µ–Ω–∏–µ –∫ –±–∞–∑–µ
engine = create_engine("postgresql+psycopg2://airflow:airflow@postgres-db:5432/learn_base")

def create_tables():
    """–°–æ–∑–¥–∞–Ω–∏–µ –≤—Å–µ—Ö —Ç–∞–±–ª–∏—Ü"""

    tables_sql = [
        # 1. –¢–∞–±–ª–∏—Ü–∞ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π
        """
        DROP TABLE IF EXISTS users CASCADE;
        CREATE TABLE users (
            user_id SERIAL PRIMARY KEY,
            first_name VARCHAR(50),
            last_name VARCHAR(50),
            email VARCHAR(100),
            age INTEGER,
            city VARCHAR(50),
            registration_date DATE,
            premium_user BOOLEAN DEFAULT FALSE
        );
        """,

        # 2. –¢–∞–±–ª–∏—Ü–∞ –ø—Ä–æ–¥—É–∫—Ç–æ–≤
        """
        DROP TABLE IF EXISTS products CASCADE;
        CREATE TABLE products (
            product_id SERIAL PRIMARY KEY,
            product_name VARCHAR(100),
            category VARCHAR(50),
            price DECIMAL(10,2),
            cost DECIMAL(10,2),
            stock_quantity INTEGER,
            supplier VARCHAR(100),
            created_date DATE
        );
        """,

        # 3. –¢–∞–±–ª–∏—Ü–∞ –∑–∞–∫–∞–∑–æ–≤
        """
        DROP TABLE IF EXISTS orders CASCADE;
        CREATE TABLE orders (
            order_id SERIAL PRIMARY KEY,
            user_id INTEGER REFERENCES users(user_id),
            order_date TIMESTAMP,
            total_amount DECIMAL(10,2),
            status VARCHAR(20),
            payment_method VARCHAR(50)
        );
        """,

        # 4. –¢–∞–±–ª–∏—Ü–∞ –¥–µ—Ç–∞–ª–µ–π –∑–∞–∫–∞–∑–æ–≤
        """
        DROP TABLE IF EXISTS order_items CASCADE;
        CREATE TABLE order_items (
            order_item_id SERIAL PRIMARY KEY,
            order_id INTEGER REFERENCES orders(order_id),
            product_id INTEGER REFERENCES products(product_id),
            quantity INTEGER,
            unit_price DECIMAL(10,2),
            discount DECIMAL(5,2) DEFAULT 0
        );
        """,

        # 5. –¢–∞–±–ª–∏—Ü–∞ —Å–æ—Ç—Ä—É–¥–Ω–∏–∫–æ–≤
        """
        DROP TABLE IF EXISTS employees CASCADE;
        CREATE TABLE employees (
            employee_id SERIAL PRIMARY KEY,
            first_name VARCHAR(50),
            last_name VARCHAR(50),
            department VARCHAR(50),
            salary DECIMAL(10,2),
            hire_date DATE,
            manager_id INTEGER
        );
        """,

        # 6. –¢–∞–±–ª–∏—Ü–∞ –≤–µ–±-—Ç—Ä–∞—Ñ–∏–∫–∞
        """
        DROP TABLE IF EXISTS web_traffic CASCADE;
        CREATE TABLE web_traffic (
            session_id VARCHAR(50) PRIMARY KEY,
            user_id INTEGER REFERENCES users(user_id),
            page_url VARCHAR(200),
            session_duration INTEGER,
            page_views INTEGER,
            traffic_source VARCHAR(50),
            event_date TIMESTAMP
        );
        """
    ]

    with engine.begin() as conn:
        for sql in tables_sql:
            conn.execute(text(sql))
    print("‚úÖ –í—Å–µ —Ç–∞–±–ª–∏—Ü—ã —Å–æ–∑–¥–∞–Ω—ã")

def generate_users_data():
    """–ì–µ–Ω–µ—Ä–∞—Ü–∏—è –¥–∞–Ω–Ω—ã—Ö –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π"""
    first_names = ['–ò–≤–∞–Ω', '–ú–∞—Ä–∏—è', '–ê–ª–µ–∫—Å–µ–π', '–û–ª—å–≥–∞', '–î–º–∏—Ç—Ä–∏–π', '–ï–ª–µ–Ω–∞', '–°–µ—Ä–≥–µ–π', '–ê–Ω–Ω–∞', '–ê–Ω–¥—Ä–µ–π', '–ù–∞—Ç–∞–ª—å—è']
    last_names = ['–ò–≤–∞–Ω–æ–≤', '–ü–µ—Ç—Ä–æ–≤–∞', '–°–∏–¥–æ—Ä–æ–≤', '–°–º–∏—Ä–Ω–æ–≤–∞', '–ö—É–∑–Ω–µ—Ü–æ–≤', '–ü–æ–ø–æ–≤–∞', '–í–∞—Å–∏–ª—å–µ–≤', '–ù–æ–≤–∏–∫–æ–≤–∞', '–§–µ–¥–æ—Ä–æ–≤', '–ú–æ—Ä–æ–∑–æ–≤–∞']
    cities = ['–ú–æ—Å–∫–≤–∞', '–°–∞–Ω–∫—Ç-–ü–µ—Ç–µ—Ä–±—É—Ä–≥', '–ù–æ–≤–æ—Å–∏–±–∏—Ä—Å–∫', '–ï–∫–∞—Ç–µ—Ä–∏–Ω–±—É—Ä–≥', '–ö–∞–∑–∞–Ω—å', '–ù–∏–∂–Ω–∏–π –ù–æ–≤–≥–æ—Ä–æ–¥', '–ß–µ–ª—è–±–∏–Ω—Å–∫', '–°–∞–º–∞—Ä–∞', '–û–º—Å–∫', '–†–æ—Å—Ç–æ–≤-–Ω–∞-–î–æ–Ω—É']

    users = []
    for i in range(100):
        user = {
            'first_name': random.choice(first_names),
            'last_name': random.choice(last_names),
            'email': f"user{i+1}@example.com",
            'age': random.randint(18, 65),
            'city': random.choice(cities),
            'registration_date': datetime.now() - timedelta(days=random.randint(1, 365)),
            'premium_user': random.choice([True, False, False, False])  # 25% –ø—Ä–µ–º–∏—É–º
        }
        users.append(user)

    df_users = pd.DataFrame(users)
    df_users.to_sql('users', engine, if_exists='append', index=False)

    # –ü–æ–ª—É—á–∞–µ–º –¥–∞–Ω–Ω—ã–µ –æ–±—Ä–∞—Ç–Ω–æ —Å user_id
    df_users_with_id = pd.read_sql("SELECT * FROM users", engine)
    print("‚úÖ –î–∞–Ω–Ω—ã–µ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π —Å–≥–µ–Ω–µ—Ä–∏—Ä–æ–≤–∞–Ω—ã")
    return df_users_with_id

def generate_products_data():
    """–ì–µ–Ω–µ—Ä–∞—Ü–∏—è –¥–∞–Ω–Ω—ã—Ö –ø—Ä–æ–¥—É–∫—Ç–æ–≤"""
    categories = {
        '–≠–ª–µ–∫—Ç—Ä–æ–Ω–∏–∫–∞': ['–°–º–∞—Ä—Ç—Ñ–æ–Ω', '–ù–æ—É—Ç–±—É–∫', '–ù–∞—É—à–Ω–∏–∫–∏', '–ü–ª–∞–Ω—à–µ—Ç', '–£–º–Ω—ã–µ —á–∞—Å—ã'],
        '–û–¥–µ–∂–¥–∞': ['–§—É—Ç–±–æ–ª–∫–∞', '–î–∂–∏–Ω—Å—ã', '–ü–ª–∞—Ç—å–µ', '–ö—É—Ä—Ç–∫–∞', '–û–±—É–≤—å'],
        '–ö–Ω–∏–≥–∏': ['–†–æ–º–∞–Ω', '–î–µ—Ç–µ–∫—Ç–∏–≤', '–§–∞–Ω—Ç–∞—Å—Ç–∏–∫–∞', '–ë–∏–∑–Ω–µ—Å-–ª–∏—Ç–µ—Ä–∞—Ç—É—Ä–∞', '–ù–∞—É–∫–∞'],
        '–î–æ–º': ['–ú–µ–±–µ–ª—å', '–ü–æ—Å—É–¥–∞', '–¢–µ–∫—Å—Ç–∏–ª—å', '–û—Å–≤–µ—â–µ–Ω–∏–µ', '–î–µ–∫–æ—Ä']
    }

    suppliers = ['TechCorp', 'FashionStyle', 'BookWorld', 'HomeComfort', 'GlobalGoods']

    products = []
    for category, items in categories.items():
        for item in items:
            price = round(random.uniform(10, 1000), 2)
            cost = round(price * random.uniform(0.3, 0.7), 2)
            product = {
                'product_name': f"{item} {random.choice(['Pro', 'Lite', 'Max', 'Standard', 'Premium'])}",
                'category': category,
                'price': price,
                'cost': cost,
                'stock_quantity': random.randint(0, 500),
                'supplier': random.choice(suppliers),
                'created_date': datetime.now() - timedelta(days=random.randint(30, 365))
            }
            products.append(product)

    df_products = pd.DataFrame(products)
    df_products.to_sql('products', engine, if_exists='append', index=False)

    # –ü–æ–ª—É—á–∞–µ–º –¥–∞–Ω–Ω—ã–µ –æ–±—Ä–∞—Ç–Ω–æ —Å product_id
    df_products_with_id = pd.read_sql("SELECT * FROM products", engine)
    print("‚úÖ –î–∞–Ω–Ω—ã–µ –ø—Ä–æ–¥—É–∫—Ç–æ–≤ —Å–≥–µ–Ω–µ—Ä–∏—Ä–æ–≤–∞–Ω—ã")
    return df_products_with_id

def generate_orders_data(users_df, products_df):
    """–ì–µ–Ω–µ—Ä–∞—Ü–∏—è –¥–∞–Ω–Ω—ã—Ö –∑–∞–∫–∞–∑–æ–≤"""
    statuses = ['completed', 'pending', 'cancelled', 'shipped']
    payment_methods = ['credit_card', 'paypal', 'bank_transfer', 'cash']

    orders = []
    order_items = []

    for order_id in range(1, 201):
        user_id = random.choice(users_df['user_id'].values)
        order_date = datetime.now() - timedelta(days=random.randint(1, 90),
                                              hours=random.randint(1, 23),
                                              minutes=random.randint(1, 59))

        # –°–æ–∑–¥–∞–µ–º –∑–∞–∫–∞–∑
        order = {
            'user_id': user_id,
            'order_date': order_date,
            'total_amount': 0,  # –ø–æ—Å—á–∏—Ç–∞–µ–º –Ω–∏–∂–µ
            'status': random.choice(statuses),
            'payment_method': random.choice(payment_methods)
        }
        orders.append(order)

        # –î–æ–±–∞–≤–ª—è–µ–º —Ç–æ–≤–∞—Ä—ã –≤ –∑–∞–∫–∞–∑
        total_amount = 0
        num_items = random.randint(1, 5)
        for _ in range(num_items):
            product = products_df.sample(1).iloc[0]
            quantity = random.randint(1, 3)
            unit_price = float(product['price']) * random.uniform(0.9, 1.0)  # –Ω–µ–±–æ–ª—å—à–∞—è —Å–∫–∏–¥–∫–∞
            discount = random.choice([0, 0, 0, 0.1, 0.15, 0.2])  # —Å–ª—É—á–∞–π–Ω–∞—è —Å–∫–∏–¥–∫–∞

            order_item = {
                'order_id': order_id,
                'product_id': product['product_id'],
                'quantity': quantity,
                'unit_price': round(unit_price, 2),
                'discount': discount
            }
            order_items.append(order_item)

            total_amount += unit_price * quantity * (1 - discount)

        # –û–±–Ω–æ–≤–ª—è–µ–º –æ–±—â—É—é —Å—É–º–º—É –∑–∞–∫–∞–∑–∞
        orders[-1]['total_amount'] = round(total_amount, 2)

    # –í—Å—Ç–∞–≤–ª—è–µ–º –∑–∞–∫–∞–∑—ã
    df_orders = pd.DataFrame(orders)
    df_orders.to_sql('orders', engine, if_exists='append', index=False)

    # –í—Å—Ç–∞–≤–ª—è–µ–º —ç–ª–µ–º–µ–Ω—Ç—ã –∑–∞–∫–∞–∑–æ–≤
    df_order_items = pd.DataFrame(order_items)
    df_order_items.to_sql('order_items', engine, if_exists='append', index=False)

    print("‚úÖ –î–∞–Ω–Ω—ã–µ –∑–∞–∫–∞–∑–æ–≤ —Å–≥–µ–Ω–µ—Ä–∏—Ä–æ–≤–∞–Ω—ã")
    return df_orders, df_order_items

def generate_employees_data():
    """–ì–µ–Ω–µ—Ä–∞—Ü–∏—è –¥–∞–Ω–Ω—ã—Ö —Å–æ—Ç—Ä—É–¥–Ω–∏–∫–æ–≤"""
    departments = ['IT', 'Marketing', 'Sales', 'HR', 'Finance', 'Operations']

    # –°–Ω–∞—á–∞–ª–∞ —Å–æ–∑–¥–∞–µ–º –º–µ–Ω–µ–¥–∂–µ—Ä–æ–≤
    managers_data = []
    manager_ids = {}

    for i, dept in enumerate(departments[:5]):  # 5 –º–µ–Ω–µ–¥–∂–µ—Ä–æ–≤
        manager = {
            'first_name': random.choice(['–ê–ª–µ–∫—Å–∞–Ω–¥—Ä', '–ï–∫–∞—Ç–µ—Ä–∏–Ω–∞', '–ú–∏—Ö–∞–∏–ª', '–¢–∞—Ç—å—è–Ω–∞', '–í–ª–∞–¥–∏–º–∏—Ä']),
            'last_name': random.choice(['–°–æ–∫–æ–ª–æ–≤', '–û—Ä–ª–æ–≤–∞', '–õ–µ–±–µ–¥–µ–≤', '–ö–æ–≤–∞–ª–µ–≤–∞', '–ù–∏–∫–∏—Ç–∏–Ω']),
            'department': dept,
            'salary': round(random.uniform(80000, 150000), 2),
            'hire_date': datetime.now() - timedelta(days=random.randint(365, 1825)),
            'manager_id': None
        }
        managers_data.append(manager)

    # –í—Å—Ç–∞–≤–ª—è–µ–º –º–µ–Ω–µ–¥–∂–µ—Ä–æ–≤ –∏ –ø–æ–ª—É—á–∞–µ–º –∏—Ö ID
    df_managers = pd.DataFrame(managers_data)
    df_managers.to_sql('employees', engine, if_exists='append', index=False)

    # –ü–æ–ª—É—á–∞–µ–º ID –º–µ–Ω–µ–¥–∂–µ—Ä–æ–≤
    managers_df = pd.read_sql("SELECT employee_id, department FROM employees WHERE manager_id IS NULL", engine)
    manager_ids = dict(zip(managers_df['department'], managers_df['employee_id']))

    # –¢–µ–ø–µ—Ä—å —Å–æ–∑–¥–∞–µ–º –æ–±—ã—á–Ω—ã—Ö —Å–æ—Ç—Ä—É–¥–Ω–∏–∫–æ–≤
    employees_data = []
    for i in range(20):
        department = random.choice(departments)
        manager_id = manager_ids.get(department)

        employee = {
            'first_name': random.choice(['–ê–Ω–Ω–∞', '–î–º–∏—Ç—Ä–∏–π', '–û–ª—å–≥–∞', '–ò–≥–æ—Ä—å', '–°–≤–µ—Ç–ª–∞–Ω–∞', '–ü–∞–≤–µ–ª', '–Æ–ª–∏—è', '–ê—Ä—Ç–µ–º']),
            'last_name': random.choice(['–ò–≤–∞–Ω–æ–≤–∞', '–ü–µ—Ç—Ä–æ–≤', '–°–∏–¥–æ—Ä–æ–≤–∞', '–ö–æ–∑–ª–æ–≤', '–§—Ä–æ–ª–æ–≤–∞', '–ñ—É–∫–æ–≤', '–ú–∞–∫—Å–∏–º–æ–≤–∞', '–ë–µ–ª–æ–≤']),
            'department': department,
            'salary': round(random.uniform(40000, 90000), 2),
            'hire_date': datetime.now() - timedelta(days=random.randint(30, 1095)),
            'manager_id': manager_id
        }
        employees_data.append(employee)

    # –í—Å—Ç–∞–≤–ª—è–µ–º –æ–±—ã—á–Ω—ã—Ö —Å–æ—Ç—Ä—É–¥–Ω–∏–∫–æ–≤
    df_employees = pd.DataFrame(employees_data)
    df_employees.to_sql('employees', engine, if_exists='append', index=False)

    # –ü–æ–ª—É—á–∞–µ–º –≤—Å–µ—Ö —Å–æ—Ç—Ä—É–¥–Ω–∏–∫–æ–≤
    all_employees = pd.read_sql("SELECT * FROM employees", engine)
    print("‚úÖ –î–∞–Ω–Ω—ã–µ —Å–æ—Ç—Ä—É–¥–Ω–∏–∫–æ–≤ —Å–≥–µ–Ω–µ—Ä–∏—Ä–æ–≤–∞–Ω—ã")
    return all_employees

def generate_web_traffic_data(users_df):
    """–ì–µ–Ω–µ—Ä–∞—Ü–∏—è –¥–∞–Ω–Ω—ã—Ö –≤–µ–±-—Ç—Ä–∞—Ñ–∏–∫–∞"""
    pages = ['/home', '/products', '/about', '/contact', '/blog', '/cart', '/checkout']
    traffic_sources = ['organic', 'direct', 'social', 'email', 'referral']

    web_traffic = []

    for i in range(300):
        # 70% —Å–µ—Å—Å–∏–π —Å –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è–º–∏, 30% –±–µ–∑
        user_id = random.choice(users_df['user_id'].tolist()) if random.random() < 0.7 else None
        session_id = f"session_{i+1}_{random.randint(1000, 9999)}"

        traffic = {
            'session_id': session_id,
            'user_id': user_id,
            'page_url': random.choice(pages),
            'session_duration': random.randint(10, 1800),
            'page_views': random.randint(1, 20),
            'traffic_source': random.choice(traffic_sources),
            'event_date': datetime.now() - timedelta(days=random.randint(0, 30),
                                                   hours=random.randint(0, 23),
                                                   minutes=random.randint(0, 59))
        }
        web_traffic.append(traffic)

    df_web_traffic = pd.DataFrame(web_traffic)
    df_web_traffic.to_sql('web_traffic', engine, if_exists='append', index=False)
    print("‚úÖ –î–∞–Ω–Ω—ã–µ –≤–µ–±-—Ç—Ä–∞—Ñ–∏–∫–∞ —Å–≥–µ–Ω–µ—Ä–∏—Ä–æ–≤–∞–Ω—ã")
    return df_web_traffic

def main():
    """–û—Å–Ω–æ–≤–Ω–∞—è —Ñ—É–Ω–∫—Ü–∏—è –≥–µ–Ω–µ—Ä–∞—Ü–∏–∏ –≤—Å–µ—Ö –¥–∞–Ω–Ω—ã—Ö"""
    print("üöÄ –ù–∞—á–∏–Ω–∞–µ–º –≥–µ–Ω–µ—Ä–∞—Ü–∏—é —Ç–µ—Å—Ç–æ–≤—ã—Ö –¥–∞–Ω–Ω—ã—Ö...")

    # –°–æ–∑–¥–∞–µ–º —Ç–∞–±–ª–∏—Ü—ã
    create_tables()

    # –ì–µ–Ω–µ—Ä–∏—Ä—É–µ–º –¥–∞–Ω–Ω—ã–µ –≤ –ø—Ä–∞–≤–∏–ª—å–Ω–æ–º –ø–æ—Ä—è–¥–∫–µ
    users_df = generate_users_data()
    products_df = generate_products_data()
    orders_df, order_items_df = generate_orders_data(users_df, products_df)
    employees_df = generate_employees_data()
    web_traffic_df = generate_web_traffic_data(users_df)

    print("\nüéâ –í—Å–µ –¥–∞–Ω–Ω—ã–µ —É—Å–ø–µ—à–Ω–æ —Å–≥–µ–Ω–µ—Ä–∏—Ä–æ–≤–∞–Ω—ã!")
    print("\nüìä –°–æ–∑–¥–∞–Ω–Ω—ã–µ —Ç–∞–±–ª–∏—Ü—ã –∏ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –∑–∞–ø–∏—Å–µ–π:")
    print(f"  ‚Ä¢ users: {len(users_df)} –∑–∞–ø–∏—Å–µ–π")
    print(f"  ‚Ä¢ products: {len(products_df)} –∑–∞–ø–∏—Å–µ–π")
    print(f"  ‚Ä¢ orders: {len(orders_df)} –∑–∞–ø–∏—Å–µ–π")
    print(f"  ‚Ä¢ order_items: {len(order_items_df)} –∑–∞–ø–∏—Å–µ–π")
    print(f"  ‚Ä¢ employees: {len(employees_df)} –∑–∞–ø–∏—Å–µ–π")
    print(f"  ‚Ä¢ web_traffic: {len(web_traffic_df)} –∑–∞–ø–∏—Å–µ–π")

    # –ü–æ–∫–∞–∑—ã–≤–∞–µ–º –ø—Ä–∏–º–µ—Ä—ã –¥–∞–Ω–Ω—ã—Ö
    print("\nüîç –ü—Ä–∏–º–µ—Ä –¥–∞–Ω–Ω—ã—Ö –∏–∑ —Ç–∞–±–ª–∏—Ü—ã products:")
    sample_products = pd.read_sql("SELECT * FROM products LIMIT 5", engine)
    print(sample_products.to_string(index=False))

# –ó–∞–ø—É—Å–∫ –≥–µ–Ω–µ—Ä–∞—Ü–∏–∏
if __name__ == "__main__":
    main()

üöÄ –ù–∞—á–∏–Ω–∞–µ–º –≥–µ–Ω–µ—Ä–∞—Ü–∏—é —Ç–µ—Å—Ç–æ–≤—ã—Ö –¥–∞–Ω–Ω—ã—Ö...
‚úÖ –í—Å–µ —Ç–∞–±–ª–∏—Ü—ã —Å–æ–∑–¥–∞–Ω—ã
‚úÖ –î–∞–Ω–Ω—ã–µ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π —Å–≥–µ–Ω–µ—Ä–∏—Ä–æ–≤–∞–Ω—ã
‚úÖ –î–∞–Ω–Ω—ã–µ –ø—Ä–æ–¥—É–∫—Ç–æ–≤ —Å–≥–µ–Ω–µ—Ä–∏—Ä–æ–≤–∞–Ω—ã
‚úÖ –î–∞–Ω–Ω—ã–µ –∑–∞–∫–∞–∑–æ–≤ —Å–≥–µ–Ω–µ—Ä–∏—Ä–æ–≤–∞–Ω—ã
‚úÖ –î–∞–Ω–Ω—ã–µ —Å–æ—Ç—Ä—É–¥–Ω–∏–∫–æ–≤ —Å–≥–µ–Ω–µ—Ä–∏—Ä–æ–≤–∞–Ω—ã
‚úÖ –î–∞–Ω–Ω—ã–µ –≤–µ–±-—Ç—Ä–∞—Ñ–∏–∫–∞ —Å–≥–µ–Ω–µ—Ä–∏—Ä–æ–≤–∞–Ω—ã

üéâ –í—Å–µ –¥–∞–Ω–Ω—ã–µ —É—Å–ø–µ—à–Ω–æ —Å–≥–µ–Ω–µ—Ä–∏—Ä–æ–≤–∞–Ω—ã!

üìä –°–æ–∑–¥–∞–Ω–Ω—ã–µ —Ç–∞–±–ª–∏—Ü—ã –∏ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –∑–∞–ø–∏—Å–µ–π:
  ‚Ä¢ users: 100 –∑–∞–ø–∏—Å–µ–π
  ‚Ä¢ products: 20 –∑–∞–ø–∏—Å–µ–π
  ‚Ä¢ orders: 200 –∑–∞–ø–∏—Å–µ–π
  ‚Ä¢ order_items: 581 –∑–∞–ø–∏—Å–µ–π
  ‚Ä¢ employees: 25 –∑–∞–ø–∏—Å–µ–π
  ‚Ä¢ web_traffic: 300 –∑–∞–ø–∏—Å–µ–π

üîç –ü—Ä–∏–º–µ—Ä –¥–∞–Ω–Ω—ã—Ö –∏–∑ —Ç–∞–±–ª–∏—Ü—ã products:
 product_id    product_name    category  price   cost  stock_quantity     supplier created_date
          1   –°–º–∞—Ä—Ç—Ñ–æ–Ω Lite –≠–ª–µ–∫—Ç—Ä–æ–Ω–∏–∫–∞ 556.86 350.16             112  HomeComfort   2025-05-08
          2     –ù–æ—É—Ç–±—É–∫ Pro –≠–ª–µ–∫—Ç—Ä–æ–Ω–∏–∫–∞ 107.06  46.17             289  HomeComfort   2025-08-28
          3    –ù–∞—É—à–Ω–∏–∫–∏ Pro –≠–ª–µ–∫—Ç—Ä–æ–Ω–∏–∫–∞ 952.31 455.59             429  GlobalGoods   2025-01-29
          4 –ü–ª–∞–Ω—à–µ—Ç Premium –≠–ª–µ–∫—Ç—Ä–æ–Ω–∏–∫–∞  95.13  65.84             197 FashionStyle   2025-09-06
          5 –£–º–Ω—ã–µ —á–∞—Å—ã Lite –≠–ª–µ–∫—Ç—Ä–æ–Ω–∏–∫–∞ 757.27 309.20             175 FashionStyle   2025-03-19